services:
  payment:
    build:
      context: .
      dockerfile: ./services/payment/Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://user:password@payment-db:5432/hexabank?sslmode=disable
      FRAUD_SERVICE_ADDRESS: fraud:50052
    depends_on:
      payment-db:
        condition: service_healthy

  payment-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hexabank
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d hexabank"]
      interval: 5s
      timeout: 5s
      retries: 5

  payment-db-migrations:
    image: ghcr.io/kukymbr/goose-docker:3.24.1
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=payment-db port=5432 user=user password=password dbname=hexabank
    volumes:
      - ./services/payment/adapters/postgres/migrations:/migrations
    depends_on:
      - payment-db

  fraud:
    build:
      context: .
      dockerfile: ./services/fraud/Dockerfile
    ports:
      - "50052:50052"
