services:
  payment:
    build:
      context: .
      dockerfile: ./services/payment/Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://user:password@payment-db:5432/hexabank?sslmode=disable
      FRAUD_SERVICE_ADDRESS: fraud:50052
      OTLP_ENDPOINT: tempo:4318
    depends_on:
      payment-db:
        condition: service_healthy

  payment-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hexabank
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d hexabank"]
      interval: 5s
      timeout: 5s
      retries: 5

  payment-db-migrations:
    image: ghcr.io/kukymbr/goose-docker:3.24.1
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=payment-db port=5432 user=user password=password dbname=hexabank
    volumes:
      - ./services/payment/adapters/postgres/migrations:/migrations
    depends_on:
      - payment-db

  fraud:
    build:
      context: .
      dockerfile: ./services/fraud/Dockerfile
    ports:
      - "50052:50052"
    environment:
      OTLP_ENDPOINT: tempo:4318

  tempo:
    image: grafana/tempo
    command: ["-config.file=/etc/tempo/tempo.yaml"]
    volumes:
      - ./internal/observability/tracing/tempo-config.yaml:/etc/tempo/tempo.yaml
    ports:
      - "4318:4318"
      - "3200:3200"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - tempo
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_THEME: "light"
