// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/proto/fraud/fraud.proto

package fraud

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRequest) Reset() {
	*x = PaymentRequest{}
	mi := &file_api_proto_fraud_fraud_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequest) ProtoMessage() {}

func (x *PaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fraud_fraud_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequest.ProtoReflect.Descriptor instead.
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fraud_fraud_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type FraudResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFraudulent  bool                   `protobuf:"varint,1,opt,name=isFraudulent,proto3" json:"isFraudulent,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FraudResponse) Reset() {
	*x = FraudResponse{}
	mi := &file_api_proto_fraud_fraud_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudResponse) ProtoMessage() {}

func (x *FraudResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fraud_fraud_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudResponse.ProtoReflect.Descriptor instead.
func (*FraudResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_fraud_fraud_proto_rawDescGZIP(), []int{1}
}

func (x *FraudResponse) GetIsFraudulent() bool {
	if x != nil {
		return x.IsFraudulent
	}
	return false
}

func (x *FraudResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_fraud_fraud_proto protoreflect.FileDescriptor

const file_api_proto_fraud_fraud_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/fraud/fraud.proto\x12\x05order\"8\n" +
	"\x0ePaymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\"M\n" +
	"\rFraudResponse\x12\"\n" +
	"\fisFraudulent\x18\x01 \x01(\bR\fisFraudulent\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2P\n" +
	"\fFraudService\x12@\n" +
	"\x11FraudCheckHandler\x12\x15.order.PaymentRequest\x1a\x14.order.FraudResponseB\x1aZ\x18hexabank/api/proto/fraudb\x06proto3"

var (
	file_api_proto_fraud_fraud_proto_rawDescOnce sync.Once
	file_api_proto_fraud_fraud_proto_rawDescData []byte
)

func file_api_proto_fraud_fraud_proto_rawDescGZIP() []byte {
	file_api_proto_fraud_fraud_proto_rawDescOnce.Do(func() {
		file_api_proto_fraud_fraud_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_fraud_fraud_proto_rawDesc), len(file_api_proto_fraud_fraud_proto_rawDesc)))
	})
	return file_api_proto_fraud_fraud_proto_rawDescData
}

var file_api_proto_fraud_fraud_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_fraud_fraud_proto_goTypes = []any{
	(*PaymentRequest)(nil), // 0: order.PaymentRequest
	(*FraudResponse)(nil),  // 1: order.FraudResponse
}
var file_api_proto_fraud_fraud_proto_depIdxs = []int32{
	0, // 0: order.FraudService.FraudCheckHandler:input_type -> order.PaymentRequest
	1, // 1: order.FraudService.FraudCheckHandler:output_type -> order.FraudResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_fraud_fraud_proto_init() }
func file_api_proto_fraud_fraud_proto_init() {
	if File_api_proto_fraud_fraud_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_fraud_fraud_proto_rawDesc), len(file_api_proto_fraud_fraud_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_fraud_fraud_proto_goTypes,
		DependencyIndexes: file_api_proto_fraud_fraud_proto_depIdxs,
		MessageInfos:      file_api_proto_fraud_fraud_proto_msgTypes,
	}.Build()
	File_api_proto_fraud_fraud_proto = out.File
	file_api_proto_fraud_fraud_proto_goTypes = nil
	file_api_proto_fraud_fraud_proto_depIdxs = nil
}
